# Generated by Django 5.2.6 on 2025-09-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
